import type { Metadata } from "next";
import "./globals.css";
import Container from "@/components/container";
import Footer from "@/components/footer";
import Header  from "@/components/header";

import { Outfit } from 'next/font/google';


export const metadata: Metadata = {
  title: "Xcom data",
  description: "Generated by create next app",
};

const outfit = Outfit({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={`${outfit.className} text-zinc-900 bg-zinc-100  min-h-screen `}>
        <Container>
          <Header />
          {children}
          <Footer />
        </Container>
      </body>
    </html>
  );
}
