import type { Metadata } from 'next'
import './globals.css'

import { Outfit } from 'next/font/google'
import Providers from '@/components/layout/providers'

export const metadata: Metadata = {
    title: 'Xcom data',
    description: 'Generated by create next app'
}

const outfit = Outfit({ subsets: ['latin'] })

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en' suppressHydrationWarning className='light'>
            <body className={`${outfit.className} min-h-full bg-zinc-100`}>
                <Providers>{children}</Providers>
            </body>
        </html>
    )
}
